default:
  site:
    review_period: '13 months'
    spaces:
      - space_path: java
        space_name: Client SDK - Java
    branch: master
    dev_browser_path: java
    versions:
      - label: Java Rolling Release
        is_current_version: true
development:
  isDev: true
