default:
  site:
    review_period: '13 months'
    spaces:
      - space_path: java
        space_name: Java Client SDK
    branch: master
    dev_browser_path: java
    versions:
      - label: Java 3.2
        url_path: '3.2'
        is_current_version: true
development:
  isDev: true
