default:
  site:
    review_period: '13 months'
    default_space: 'client'
    spaces:
      -
        space_path: clients/java
        space_name: Client SDK - Java
    dev_browser_path: /
  verify_paths:
    - index.html
development:
  isDev: true
