default:
  site:
    review_period: '13 months'
    spaces:
      -
        space_path: java
        space_name: Client SDK - Java
    branch: '3.1'
    dev_browser_path: /java
    versions:
      - label: Java 3.1
        url_path: '3.1'
        is_current_version: true
development:
  isDev: true
