default:
  site:
    review_period: '13 months'
    spaces:
      - space_path: client-java
        space_name: Java Client SDK
    branch: master
    dev_browser_path: client-java
    versions:
      - label: Java 3.13
        url_path: '3.13'
        is_current_version: true
      - label: Java 3.12
        url_path: '3.12'
      - label: Java 3.11
        url_path: '3.11'
      - label: Java 3.10
        url_path: '3.10'
      - label: Java 3.9
        url_path: '3.9'
      - label: Java 3.8
        url_path: '3.8'
      - label: Java 3.7
        url_path: '3.7'
      - label: Java 3.6
        url_path: '3.6'
      - label: Java 3.5
        url_path: '3.5'
      - label: Java 3.4
        url_path: '3.4'
      - label: Java 3.3
        url_path: '3.3'
      - label: Java 3.2
        url_path: '3.2'
development:
  isDev: true
