default:
  site:
    review_period: '13 months'
    spaces:
      -
        space_path: clients/java
        space_name: Client SDK - Java
    dev_browser_path: nxdoc
  verify_paths:
    - nxdoc
    - userdoc
    - nxdoc/index.html
development:
  isDev: true
